[alias]
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --release -- time"

# [env]
# Z3_LIBRARY_PATH_OVERRIDE = "/opt/homebrew/lib"
# Z3_SYS_Z3_HEADER = "/opt/homebrew/include/z3.h"
